#!/usr/bin/env bash
set -euo pipefail

# Build lex-lsp with local dependencies
# Patches editors/ to use local lex-babel and lex-core, builds the binary,
# and places it in a known location for local development.

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
WORKSPACE_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"

EDITORS_DIR="$WORKSPACE_DIR/editors"
TOOLS_DIR="$WORKSPACE_DIR/tools"
CORE_DIR="$WORKSPACE_DIR/core"
OUTPUT_DIR="$WORKSPACE_DIR/target/local"

# Parse arguments
RELEASE=true
CLEAN=false
VERBOSE=false

usage() {
  cat <<EOF
Usage: $(basename "$0") [OPTIONS]

Builds lex-lsp binary using local workspace dependencies (lex-babel, lex-core).
The binary is placed in target/local/lex-lsp for use by editors.

Options:
  --debug     Build in debug mode (faster compile, slower runtime)
  --clean     Clean build artifacts before building
  --verbose   Show cargo output
  --help      Show this help message

Environment:
  LEX_LSP_PATH  After running, set this to $OUTPUT_DIR/lex-lsp
                to use the local binary with lexed/vscode/nvim.
EOF
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --debug)
      RELEASE=false
      shift
      ;;
    --clean)
      CLEAN=true
      shift
      ;;
    --verbose|-v)
      VERBOSE=true
      shift
      ;;
    --help|-h)
      usage
      exit 0
      ;;
    *)
      echo "Unknown option: $1" >&2
      usage >&2
      exit 1
      ;;
  esac
done

# Verify directories exist
for dir in "$EDITORS_DIR" "$TOOLS_DIR" "$CORE_DIR"; do
  if [[ ! -d "$dir" ]]; then
    echo "Error: Directory not found: $dir" >&2
    echo "Run scripts/setup.sh first to clone all repositories." >&2
    exit 1
  fi
done

# Create output directory
mkdir -p "$OUTPUT_DIR"

# Create .cargo/config.toml with patches
CARGO_CONFIG_DIR="$EDITORS_DIR/.cargo"
CARGO_CONFIG="$CARGO_CONFIG_DIR/config.toml"
CARGO_CONFIG_BACKUP="$CARGO_CONFIG.bak"

mkdir -p "$CARGO_CONFIG_DIR"

# Backup existing config if present
if [[ -f "$CARGO_CONFIG" ]]; then
  cp "$CARGO_CONFIG" "$CARGO_CONFIG_BACKUP"
fi

# Write patch config
cat > "$CARGO_CONFIG" << EOF
# Auto-generated by build-local.sh - DO NOT COMMIT
# Patches crates.io dependencies to use local workspace paths

[patch.crates-io]
lex-babel = { path = "../tools/lex-babel" }
lex-core = { path = "../core" }
EOF

echo "Patching editors/ to use local dependencies..."

cleanup() {
  # Restore or remove cargo config
  if [[ -f "$CARGO_CONFIG_BACKUP" ]]; then
    mv "$CARGO_CONFIG_BACKUP" "$CARGO_CONFIG"
  else
    rm -f "$CARGO_CONFIG"
    rmdir "$CARGO_CONFIG_DIR" 2>/dev/null || true
  fi
}
trap cleanup EXIT

# Build
cd "$EDITORS_DIR"

if [[ "$CLEAN" == true ]]; then
  echo "Cleaning build artifacts..."
  cargo clean
fi

# Update Cargo.lock to pick up patched versions
echo "Updating dependencies to use local versions..."
cargo update -p lex-babel -p lex-core 2>/dev/null || true

BUILD_ARGS=(build --bin lex-lsp)
if [[ "$RELEASE" == true ]]; then
  BUILD_ARGS+=(--release)
fi

echo "Building lex-lsp..."
if [[ "$VERBOSE" == true ]]; then
  cargo "${BUILD_ARGS[@]}"
else
  cargo "${BUILD_ARGS[@]}" 2>&1 | tail -5
fi

# Copy binary to output
if [[ "$RELEASE" == true ]]; then
  BINARY_SRC="$EDITORS_DIR/target/release/lex-lsp"
else
  BINARY_SRC="$EDITORS_DIR/target/debug/lex-lsp"
fi

if [[ ! -f "$BINARY_SRC" ]]; then
  echo "Error: Binary not found at $BINARY_SRC" >&2
  exit 1
fi

cp "$BINARY_SRC" "$OUTPUT_DIR/lex-lsp"
chmod +x "$OUTPUT_DIR/lex-lsp"

echo ""
echo "Build complete: $OUTPUT_DIR/lex-lsp"
echo ""
echo "To use with editors, set:"
echo "  export LEX_LSP_PATH=\"$OUTPUT_DIR/lex-lsp\""
echo ""
echo "Or for lexed:"
echo "  LEX_LSP_PATH=\"$OUTPUT_DIR/lex-lsp\" npm run dev"
